import type { Metadata } from 'next'
import { poppins, nothing_you_could_do } from './utils/fonts'
import './globals.css'
import Topbar from './components/Topbar/Topbar'

export const metadata: Metadata = {
  title: 'Next Tales',
  description: 'Next Tales - tell stories. Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppins} ${nothing_you_could_do}`}>
        <Topbar />
        {children}
      </body>
    </html>
  )
}
